/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main()
{
	int sum = 0;
	int n1 = 0, n2 = 1;
	int n3;

	do
	{
		n3 = n1 + n2;
		if((n3 % 2) == 0)
		{
			printf("\n Even fibonacci number found = %d", n3);
			sum += n3;
		}
		n1 = n2;
		n2 = n3;
	}while(n3 <= 4000000);

	printf("\n Sum of even number = %d", sum);
}
