/*
 *
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?
*/

#include <stdio.h>

#define SIZE 4000

int check_array(unsigned long long value, unsigned long long *array)
{
	int i;
	for(i=0; i<SIZE; i++)
	{
		if(value == *(array+i))
		{
			return i;
		}
	}
	return 0;
}

int main()
{
	int i, j;
	unsigned long long *pent;

	pent = malloc(sizeof(unsigned long long) * SIZE);

	for(i =0; i<SIZE; i++)
	{
		*(pent + i) = (i * (3*i-1))/2;
	}

	


#if 0
	for(i=0; i<SIZE; i++)
	{
		printf("\n [%4d], Pent = %lld", i,  *(pent+i));
	}
#else
		printf("\n [%4d], Pent = %lld", (SIZE-1),  *(pent+(SIZE-1)));
#endif
	for(i =1; i<SIZE; i++)
	{
		for(j=i+1; j<SIZE; j++)
		{
			int sum = *(pent + i) + *(pent + j);
			int sumresult = 0;
			int diffresult = 0;
			sumresult = check_array(sum, pent);
			if(sumresult != 0)
			{
				//printf("\n Sum of P[%d] + P[%d] = %d is pentagonal (P[%d])", i, j, sum, result );
				int diff = *(pent + j) - *(pent + i);
				diffresult = check_array(diff, pent);
				if(diffresult != 0)
				{
					printf("\n Sum of P[%d] + P[%d] = %d is pentagonal (P[%d]) and diff = %d is pentagonal(P[%d])", i, j, sum, sumresult, diff, diffresult);
					return;
				}
			}
			else
			{
				continue;
			}
		}
	}

	return 0;
}
