/*
 *
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

#include <stdio.h>

#define SIZE 50000

int check_array(unsigned long long value, unsigned long long *array)
{
	int i;
	for(i=0; i<SIZE; i++)
	{
		if(value == *(array+i))
		{
			return i;
		}
	}
	return 0;
}

int main()
{
	int i;
	unsigned long long *tri, *pent, *hex;

	tri = malloc(sizeof(unsigned long long) * SIZE);
	pent = malloc(sizeof(unsigned long long) * SIZE);
	hex = malloc(sizeof(unsigned long long) * SIZE);


	for(i =0; i<SIZE; i++)
	{
		*(tri + i) = (i * (i+1))/2;
		*(pent + i) = (i * (3*i-1))/2;
		*(hex + i) = (i * (2*i - 1));
	}

	


#if 0
	for(i=0; i<SIZE; i++)
	{
		printf("\n [%4d], Tri = %lld, Pent = %lldd, Hex = %lld", i, *(tri+i), *(pent+i), *(hex+i));
	}
#else
		printf("\n [%4d], Tri = %lld, Pent = %lld, Hex = %lld", (SIZE-1), *(tri+SIZE-1), *(pent+(SIZE-1)), *(hex+(SIZE-1)));
#endif
	for(i =1; i<SIZE; i++)
	{
		int result = 0;
		result = check_array(*(tri+i), pent);
		if(result != 0)
		{
			int penta = result;
			result = check_array(*(tri+i), hex);
			if(result != 0)
			{
				printf("\n Found match, Tri(%d) = Pent(%d) = Hex(%d) = %lld", i, penta, result,  *(tri+i));
			}
		}
		else
		{
			continue;
		}
	}

	return 0;
}
